################### Navigation principale ####################

[[main]]
name = "Accueil"
url = "/"
weight = 1

[[main]]
name = "L'équipe"
url = "teacher/"
weight = 2

[[main]]
name = "Master HN"
url = "course/"
weight = 3

[[main]]
name = "Actualités scientifiques"
url = "research/"
weight = 4

[[main]]
name = "Blog"
url = "blog/"
weight = 5


# footer menu

[[footer]]
name = "Accueil"
url = "/"

[[footer]]
name = "L'équipe"
url = "teacher/"

[[footer]]
name = "Master HN"
url = "course/"

[[footer]]
name = "Actualités scientifiques"
url = "research/"

[[footer]]
name = "Blog"
url = "blog/"
