################### Navigation principale ####################

[[main]]
name = "À propos"
url = "about/"
weight = 1

[[main]]
name = "Formation"
url = "course/"
weight = 2

[[main]]
name = "Recherche"
url = "research/"
weight = 3

[[main]]
name = "Projets"
url = "projects/"
weight = 4

[[main]]
name = "Candidature"
url = "candidature/"
weight = 5

[[main]]
name = "Professionnel"
url = "alternance/"
weight = 6

[[main]]
name = "Blog"
url = "blog/"
weight = 7


# footer menu

[[footer]]
name = "À propos"
url = "about/"

[[footer]]
name = "La formation"
url = "course/"

[[footer]]
name = "Recherche"
url = "research/"

[[footer]]
name = "Projets"
url = "projects/"

[[footer]]
name = "Candidature"
url = "candidature/"

[[footer]]
name = "Alternance et stage"
url = "alternance/"

[[footer]]
name = "Blog"
url = "blog/"
