################### Navigation principale ####################

[[main]]
name = "L'équipe"
url = "equipe/"
weight = 1

[[main]]
name = "Le master HN"
url = "master/"
weight = 2

[[main]]
name = "Conférences"
url = "conferences/"
weight = 3

[[main]]
name = "Projets"
url = "projets/"
weight = 4

[[main]]
name = "Blog"
url = "blog/"
weight = 5


# footer menu

[[footer]]
name = "L'équipe"
url = "equipe/"

[[footer]]
name = "Le master HN"
url = "master/"

[[footer]]
name = "Conférences"
url = "conferences/"

[[footer]]
name = "Projets"
url = "projets/"

[[footer]]
name = "Blog"
url = "blog/"
